version: '3.3'

services:
    frontend:
        build: "./frontend"
        ports:
            - "8501:8501"
        restart: "always"
        networks: 
            - "aitranscript.network"
    backend:
        build: "./backend"
        ports:
            - "8000:8000"
        restart: "always"
        networks: 
            - "aitranscript.network"
networks: 
    aitranscript.network: